<a href="https://colab.research.google.com/github/anaghaaaa/FYP-/blob/main/hw1_tennis_weather_data_set.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

importing necessary libraries: NumPy for numerical computations, Pandas for data manipulation, and train_test_split from Scikit-Learn for splitting the data into training and testing sets.

In [33]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split


reads a CSV file named 'tennis.csv' and loads it into a Pandas DataFrame called data.

In [34]:
data = pd.read_csv('/content/tennis.csv')


It prints the column names of the DataFrame.

In [35]:

print(data.columns)


Index(['outlook', 'temp', 'humidity', 'windy', 'play'], dtype='object')


gives the dimension of the dataframe

In [36]:
print(data.shape)

(14, 5)


This separates the features (X) and the target variable (y) from the DataFrame.

In [37]:
X = data.drop(columns=['play'])
y = data['play']


Printing the features(X) from the dataframe 'Data'

In [38]:
print(X)

     outlook  temp humidity  windy
0      sunny   hot     high  False
1      sunny   hot     high   True
2   overcast   hot     high  False
3      rainy  mild     high  False
4      rainy  cool   normal  False
5      rainy  cool   normal   True
6   overcast  cool   normal   True
7      sunny  mild     high  False
8      sunny  cool   normal  False
9      rainy  mild   normal  False
10     sunny  mild   normal   True
11  overcast  mild     high   True
12  overcast   hot   normal  False
13     rainy  mild     high   True


Printing the target variable (y)

In [39]:
print(y)

0      no
1      no
2     yes
3     yes
4     yes
5      no
6     yes
7      no
8     yes
9     yes
10    yes
11    yes
12    yes
13     no
Name: play, dtype: object


X_encoded is created by applying one-hot encoding to the feature columns.

In [40]:
X_encoded = pd.get_dummies(X)


here, we get the dimensions of X_encoded

In [41]:
X_encoded.shape

(14, 9)

printing X_encoded. i.e. the values of X after one hot encoding

In [42]:
print(X_encoded)

    windy  outlook_overcast  outlook_rainy  outlook_sunny  temp_cool  \
0   False                 0              0              1          0   
1    True                 0              0              1          0   
2   False                 1              0              0          0   
3   False                 0              1              0          0   
4   False                 0              1              0          1   
5    True                 0              1              0          1   
6    True                 1              0              0          1   
7   False                 0              0              1          0   
8   False                 0              0              1          1   
9   False                 0              1              0          0   
10   True                 0              0              1          0   
11   True                 1              0              0          0   
12  False                 1              0              0       

The data is split into training and testing sets using the train_test_split function. 80% of the data is used for training (X_train and y_train), and 20% is used for testing (X_test and y_test).

In [43]:
X_train, X_test, y_train, y_test = train_test_split(X_encoded, y, test_size=0.2, random_state=42)


The Pandas DataFrames are converted into NumPy arrays for further computations.

In [44]:

# Convert the DataFrames to NumPy arrays
X_train = np.array(X_train)
X_test = np.array(X_test)


 str_to_float to convert strings 'yes' and 'no' to 1.0 and 0.0, Used later for the target attribute

In [45]:
# Define a custom function to convert strings to floats
def str_to_float(s):
    if s == 'yes':
        return 1.0
    elif s == 'no':
        return 0.0
    else:
        raise ValueError('Could not convert string to float: {}'.format(s))

# Convert the target variable to floats
y_train_floats = y_train.apply(str_to_float)


sigmoid for the sigmoid activation function, and sigmoid_derivative for the derivative of the sigmoid function is created here

In [46]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x.astype(float)))


In [47]:
def sigmoid_derivative(x):
    return x * (1 - x)


We define the neural network architecture: input, hidden, and output layer sizes.

In [48]:
input_size = X_train.shape[1]
hidden_size = 1
output_size = 1


In [49]:
print(input_size)

9


Random initial weights are generated for connections between input-hidden and hidden-output layers.

In [50]:
np.random.seed(0)
weights_input_hidden = np.random.uniform(-1, 1, (input_size, hidden_size))
weights_hidden_output = np.random.uniform(-1, 1, (hidden_size, output_size))


the learning rate in neural networks determines the rate at which the model's parameters are updated during training, impacting the convergence speed and stability of the optimization process.


"epoch" in neural networks represents a single iteration through the entire training dataset during the learning process. Each epoch allows the neural network to update its parameters based on the entire dataset, helping it learn and improve its performance over time.

In [51]:
learning_rate = 0.01
epochs = 5


In [52]:
X_train = np.array(X_train)


printing X_train

In [53]:
print(X_train)

[[False 1 0 0 0 1 0 0 1]
 [True 0 1 0 1 0 0 0 1]
 [False 0 0 1 1 0 0 0 1]
 [False 1 0 0 0 1 0 1 0]
 [True 0 0 1 0 1 0 1 0]
 [True 0 1 0 0 0 1 1 0]
 [False 0 1 0 1 0 0 0 1]
 [False 0 0 1 0 0 1 1 0]
 [True 0 0 1 0 0 1 0 1]
 [False 0 1 0 0 0 1 1 0]
 [True 1 0 0 1 0 0 0 1]]


The training data is reshaped to match the network's expected input format: samples, timesteps, features.

printing X_train's dimensions

In [54]:
print(X_train.shape)

(11, 9)


In [55]:
X_train = X_train.reshape((X_train.shape[0], 1, X_train.shape[1]))


In [56]:
print(X_train)

[[[False 1 0 0 0 1 0 0 1]]

 [[True 0 1 0 1 0 0 0 1]]

 [[False 0 0 1 1 0 0 0 1]]

 [[False 1 0 0 0 1 0 1 0]]

 [[True 0 0 1 0 1 0 1 0]]

 [[True 0 1 0 0 0 1 1 0]]

 [[False 0 1 0 1 0 0 0 1]]

 [[False 0 0 1 0 0 1 1 0]]

 [[True 0 0 1 0 0 1 0 1]]

 [[False 0 1 0 0 0 1 1 0]]

 [[True 1 0 0 1 0 0 0 1]]]


In [57]:
print(X_train.shape)

(11, 1, 9)


In [58]:

for epoch in range(epochs):
    hidden_input = np.dot(X_train, weights_input_hidden)
    hidden_output = sigmoid(hidden_input)
    output = np.dot(hidden_output, weights_hidden_output)
    output = sigmoid(output)

    error = y_train_floats.values.reshape(-1, 1) - output

    d_output = error * sigmoid_derivative(output)
    d_hidden_output = d_output.dot(weights_hidden_output.T) * sigmoid_derivative(hidden_output)



In [59]:
print(error)

[[[ 0.54873076]
  [-0.45126924]
  [ 0.54873076]
  [ 0.54873076]
  [-0.45126924]
  [-0.45126924]
  [ 0.54873076]
  [-0.45126924]
  [ 0.54873076]
  [ 0.54873076]
  [ 0.54873076]]

 [[ 0.54337143]
  [-0.45662857]
  [ 0.54337143]
  [ 0.54337143]
  [-0.45662857]
  [-0.45662857]
  [ 0.54337143]
  [-0.45662857]
  [ 0.54337143]
  [ 0.54337143]
  [ 0.54337143]]

 [[ 0.5409124 ]
  [-0.4590876 ]
  [ 0.5409124 ]
  [ 0.5409124 ]
  [-0.4590876 ]
  [-0.4590876 ]
  [ 0.5409124 ]
  [-0.4590876 ]
  [ 0.5409124 ]
  [ 0.5409124 ]
  [ 0.5409124 ]]

 [[ 0.54755303]
  [-0.45244697]
  [ 0.54755303]
  [ 0.54755303]
  [-0.45244697]
  [-0.45244697]
  [ 0.54755303]
  [-0.45244697]
  [ 0.54755303]
  [ 0.54755303]
  [ 0.54755303]]

 [[ 0.5453038 ]
  [-0.4546962 ]
  [ 0.5453038 ]
  [ 0.5453038 ]
  [-0.4546962 ]
  [-0.4546962 ]
  [ 0.5453038 ]
  [-0.4546962 ]
  [ 0.5453038 ]
  [ 0.5453038 ]
  [ 0.5453038 ]]

 [[ 0.54206518]
  [-0.45793482]
  [ 0.54206518]
  [ 0.54206518]
  [-0.45793482]
  [-0.45793482]
  [ 0.54206518


#for backpropagation - do later
 # Update weights for the hidden-to-output layer
    weights_hidden_output += np.dot(hidden_output.T, d_output) * learning_rate

    # Update weights for the input-to-hidden layer
    weights_input_hidden += np.dot(X_train.reshape(-1, input_size).T, d_hidden_output) * learning_rate

In [62]:
# Make predictions on the test set

hidden_input_test = np.dot(X_test, weights_input_hidden)
hidden_output_test = sigmoid(hidden_input_test)
predictions = np.dot(hidden_output_test, weights_hidden_output)
predictions = sigmoid(predictions)


In [63]:
# Print some example predictions
print(predictions[:10])


[[0.45740614]
 [0.45546738]
 [0.45569269]]


Confusion matrix

In [64]:
from sklearn.metrics import confusion_matrix

# Round the predictions to binary values (0 or 1)
rounded_predictions = (predictions > 0.5).astype(int)

# Calculate the confusion matrix
conf_matrix = confusion_matrix(y_test.apply(str_to_float), rounded_predictions)

print("Confusion Matrix:")
print(conf_matrix)


Confusion Matrix:
[[1 0]
 [2 0]]


True Positive (TP): 1
True Negative (TN): 0
False Positive (FP): 0
False Negative (FN): 2

 the model seems to have predicted the positive class (play tennis) correctly for 1 instance, but it misclassified 2 instances of the negative class (don't play tennis) as positive.

The low accuracy and high number of false negatives suggest that the model's performance might be poor.